
apiVersion: v1
kind: Config
preferences: {}

clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJU3FmZFkxTlh4YVl3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TkRBeE1EVXhNakExTVROYUZ3MHpOREF4TURJeE1qRXdNVE5hTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUNoQ0VOSXN1OWhXMnlkblkvUXE5Q1NqdHY4Y3IxVHArU2JZRUZmS3p5UlBMdG1GUjVpTFY0Z3lXMDMKY29vM1JPS3RGcDIzL0pPOWYyR1p2QzZqdEFKaXhDRjhXdThzV0RKRWd4dmRvRW9CUGVRZDZ3OGxRSzFFdXh6eQpySlhDaXd3aERvUmtYdDBsZGFVVFd5U0pjWm9OYUpUalhNYUphTWNsSUR6L3FablZvN3JxSlNjMGRkREtQcHVGCjM0WFhFckZubnhCSjUxSTV4THpZRWZOZjlHbUJRem5EUWNObmlILzhmQkd2Z3pTQ0VscU5nVC9PcGd3Zk1MYVcKampmZytOTWRNSzVxQ1dTSVNuY2NmYi85ZGJ4QnJSNCtUdGpnMncxbzNFbzdtU1haMlphMGhlc1gxc0lQSTQrUApnMW9UYzhGNWhhNE5NRTlqVFBRR0g0VGhmVDh4QWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJRVWxhcTVUMHVoWXRMLzlkZlVnTkFTZHl2QlZqQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQXhncGVWOXphZQppL2szUHZHTEdzZTlhSTkrbDRPY3JvZzNrR1BWWlkrYWE1STNDR0V6ZkdieTRsVkt1MlMwK1J2cmxzRlpXQWNYClVjYmcvNUVaU0lxUUZOVXNwZVlXc1RoNWlsQ3BRclB4OUVvUkJZbExydHBNclNtdU1mb2FRYU9PYXBmQlRlOFQKME9nR01oSENaMkVVUnhQMWEyYWQ3a3Q4NDVnRE01cDUrREJVVCtzNWlsNndxZDZyTWRuS01aU0l6T2tnVDlwLwpYbVpFdkFwL201eEJJYUpoVWYzT25yODRtZVpHSmVaZlNpSis1TFY0ZXRKMHlvZDJ6TnNPVDlzbSsvMmoxUXNzCktIb243bWRIUzF4c2dBQTJLWW9VeDVvTWpiU1I2azFGUGxHT0xMQ01QeHVMZElEVHE2TkJEMndURFFXZ3VFakwKOENGT20zUFk5STh4Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://09480815-0cf6-48e2-8b2e-f258458f9432.eu-central-1.linodelke.net:443
  name: lke149423

users:
- name: lke149423-admin
  user:
    as-user-extra: {}
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IlFfU2dRdUVVbHFoQWhnQnBlcFhCOTFlWnUzSlo5VEppamQ4TkNBNTRsbVUifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJsa2UtYWRtaW4tdG9rZW4tN3hwcnoiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoibGtlLWFkbWluIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiZWUxOGVjMDgtOTk5My00MzAyLWI0MDctZjlkM2MwMWExNTZiIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omt1YmUtc3lzdGVtOmxrZS1hZG1pbiJ9.hGl8YoNjno0OnMAFCx8eS9qXYdvCd-jLotCV1aSCjVmZGXsg3SbiHH7Ji5j0Xvp52lDzd7uG24RuwCWeuHecGm7zxHzftWazkhIpO88EvkLUzYxG_Cw5myJJJHnMZ11mJUnWgWe2OpRM98P9UzV2PXSGaGu24fayE72yLSR6LF31EgPXc5f1FkMLy0YzLw4SPxyl3ka7aEBUINbL6UwlCJAmuJ6PtUoiw6WKHLunpndDN6p8DrXRPXlpNk2jCHpeofVJDXVB9PGKaymHqlSQSXzds0bfDyrVZBFGmhV8yyfd_KzCKwiQO0wYykexmVsOwiMzNydujYjcTn3PPgbyMQ

contexts:
- context:
    cluster: lke149423
    namespace: default
    user: lke149423-admin
  name: lke149423-ctx

current-context: lke149423-ctx
