version: '3'

services:
  frontend:
    build:
      context: ./front
    ports:
      - "80:80"
    restart: always

  backend:
    build:
      context: ./back
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    restart: always

  mongo:
    image: "mongo:latest"
    restart: always
    ports:
      - "27017:27017"