---
- name: Configure sshd_config
  hosts: all
  become: yes  # This ensures that Ansible runs commands with sudo
  become_method: sudo
  tasks:
    - name: Change SSH port in sshd_config
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?Port'
        line: 'Port 2023'

    - name: Set AddressFamily to inet
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?AddressFamily'
        line: 'AddressFamily inet'

    - name: Set PermitRootLogin to no
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PermitRootLogin'
        line: 'PermitRootLogin no'

    - name: Set PubkeyAuthentication to yes
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PubkeyAuthentication'
        line: 'PubkeyAuthentication yes'

    - name: Set PasswordAuthentication to no
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PasswordAuthentication'
        line: 'PasswordAuthentication no'

    - name: Set PermitEmptyPasswords to no
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PermitEmptyPasswords'
        line: 'PermitEmptyPasswords no'

    - name: Restart SSH service
      service:
        name: sshd
        state: restarted

